# Generated by Django 2.2.5 on 2020-03-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceapp', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attdence',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='collage',
            name='department_nmaes',
        ),
        migrations.RemoveField(
            model_name='hod',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='hod',
            name='hod_collage',
        ),
        migrations.RemoveField(
            model_name='hod',
            name='hod_department',
        ),
        migrations.RemoveField(
            model_name='hod',
            name='hod_subject',
        ),
        migrations.RemoveField(
            model_name='sunbject',
            name='sunbject_collage',
        ),
        migrations.RemoveField(
            model_name='sunbject',
            name='sunbject_department',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_collage',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_department',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_subject',
        ),
        migrations.DeleteModel(
            name='admin1',
        ),
        migrations.DeleteModel(
            name='attdence',
        ),
        migrations.DeleteModel(
            name='collage',
        ),
        migrations.DeleteModel(
            name='department',
        ),
        migrations.DeleteModel(
            name='hod',
        ),
        migrations.DeleteModel(
            name='sunbject',
        ),
        migrations.DeleteModel(
            name='teacher',
        ),
    ]
