# Generated by Django 2.2.5 on 2020-03-17 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendenceapp', '0005_auto_20200316_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_id', models.CharField(blank=True, max_length=100, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('admin_email', models.EmailField(max_length=254)),
                ('admin_age', models.IntegerField()),
                ('special_status', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='attdence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100)),
                ('paid_leave', models.IntegerField()),
                ('workingdays', models.IntegerField()),
                ('count', models.IntegerField()),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('special_status', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=100)),
                ('batch_id', models.CharField(max_length=100)),
                ('batch_total_student', models.IntegerField()),
                ('batch_year', models.IntegerField()),
                ('batch_sem', models.IntegerField()),
                ('batch_createdat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='collage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collage_name', models.CharField(max_length=100, unique=True)),
                ('collage_unique_id', models.CharField(blank=True, max_length=100, null=True)),
                ('collage_reg', models.CharField(max_length=100, unique=True)),
                ('collage_address', models.CharField(max_length=100, unique=True)),
                ('createdat', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100, unique=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('department_unique_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='hod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hod_name', models.CharField(max_length=100)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('hod_email', models.EmailField(max_length=254, unique=True)),
                ('hod_id', models.CharField(blank=True, max_length=100, null=True)),
                ('hod_age', models.IntegerField()),
                ('special_status', models.BooleanField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendenceapp.admin1')),
                ('hod_collage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendenceapp.collage')),
                ('hod_department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendenceapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('student_email', models.EmailField(max_length=254, unique=True)),
                ('student_id', models.CharField(blank=True, max_length=100, null=True)),
                ('student_age', models.IntegerField()),
                ('special_status', models.BooleanField(blank=True, null=True)),
                ('student_rol_no', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendenceapp.admin1')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendenceapp.batch')),
                ('student_collage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendenceapp.collage')),
                ('student_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendenceapp.department')),
                ('student_which_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sunbject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunbject_name', models.CharField(max_length=100, unique=True)),
                ('subject_unique_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sunbject_collage', models.ManyToManyField(to='attendenceapp.collage')),
                ('sunbject_department', models.ManyToManyField(to='attendenceapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_id', models.CharField(blank=True, max_length=100, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('teacher_email', models.EmailField(max_length=254, unique=True)),
                ('teacher_age', models.IntegerField()),
                ('special_status', models.BooleanField(blank=True, null=True)),
                ('teacher_password', models.CharField(blank=True, max_length=10, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendenceapp.admin1')),
                ('teacher_collage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendenceapp.collage')),
                ('teacher_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendenceapp.department')),
                ('teacher_subject', models.ManyToManyField(to='attendenceapp.sunbject')),
            ],
        ),
        migrations.DeleteModel(
            name='product1',
        ),
        migrations.AddField(
            model_name='hod',
            name='hod_subject',
            field=models.ManyToManyField(to='attendenceapp.sunbject'),
        ),
        migrations.AddField(
            model_name='collage',
            name='department_nmaes',
            field=models.ManyToManyField(to='attendenceapp.department'),
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_collage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendenceapp.collage'),
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendenceapp.department'),
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_tutor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendenceapp.teacher'),
        ),
        migrations.AddField(
            model_name='attdence',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendenceapp.teacher'),
        ),
        migrations.AddField(
            model_name='admin1',
            name='admin1_department',
            field=models.ManyToManyField(to='attendenceapp.department'),
        ),
        migrations.AddField(
            model_name='admin1',
            name='admin_collage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendenceapp.collage'),
        ),
    ]
